image: adnrv/opencv

# Some variables to make your CI DRY
variables:
  FILE: "src/main.py"

before_script:
  # Execute any scripts here before running your code

stages:
  - exec
  - report

# This stage executes our program (previously compiled)
exec:
  stage: exec
  script:
    # Note that instead of the makefile you can just call your executable here
    - python $FILE
  artifacts:
    paths:
      - input/
      - src/
      - report/
      - o-2-a-0.jpg
      - o-2-b-0.jpg
      - o-2-c-0.jpg
      - o-5-a-0.jpg
      - o-5-b-0.jpg

report:
  image: adnrv/texlive:full
  stage: report
  script:
    - ls output/
    - cd report
    - latexmk -pdf -pdflatex="pdflatex --shell-escape %O %S" report
    # move the file to the root folder
    - mv report.pdf ../
  artifacts:
    paths:
      - report.pdf
  dependencies:
    - exec