image: adnrv/opencv

# Some variables to make your CI DRY
variables:
  FILE: "src/main.py"

before_script:
  # Execute any scripts here before running your code

stages:
  - exec

# This stage executes our program (previously compiled)
exec:
  stage: exec
  script:
    # Note that instead of the makefile you can just call your executable here
    - python $FILE
  artifacts:
    paths:
      - test.jpg


# This stage builds your report too
#report:
#  image: adnrv/texlive:full
#  stage: build
#  script:
#    - cd report
#    - latexmk -pdf -pdflatex="pdflatex --shell-escape %O %S" report
#    # move the file to the root folder
#    - mv report.pdf ../
#  artifacts:
#    paths:
#      - report.pdf
